grpc:
    port: 9109
    client:
        service-grpc:
            address: static://localhost:9103
            negotiationType: plaintext
server:
    port: 0
spring:
    application:
        name: product_microservice
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            schema: public
        password: 353062
        url: jdbc:postgresql://localhost:5433/PRODUCT-db
        username: admin
    kafka:
        producer:
            acks: all
            bootstrap-servers: localhost:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            properties:
                delivery:
                    timeout:
                        ms: 10000
                linger:
                    ms: 0
                request:
                    timeout:
                        ms: 5000
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
